//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVRLoggerReceiver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVRLoggerReceiver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;
        ///			Klima
        ///		&lt;/title&gt;
        ///		
        ///	
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///		
        ///		&lt;script type=&quot;text/javascript&quot;&gt;
        ///			$(function () {Highcharts.setOptions({
        ///	lang: {
        ///		months: [&apos;Januar&apos;, &apos;Februar&apos;, &apos;März&apos;, &apos;April&apos;, &apos;Mai&apos;, &apos;Juni&apos;,  &apos;Juli&apos;, &apos;August&apos;, &apos;September&apos;, &apos;Oktober&apos;, &apos;November&apos;, &apos;Dezember&apos;],
        ///		weekdays: [&apos;Sonntag&apos;, &apos;Montag&apos;, &apos;Dienstag&apos;, &apos;Mittwoch&apos;, &apos;Donnerstag&apos;, &apos;Freitag&apos;, &apos;Samstag&apos;],
        ///		s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Graph_P1 {
            get {
                return ResourceManager.GetString("Graph_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///							],
        ///						yAxis: 0,
        ///						color: &apos;#C05555&apos;
        ///					},
        ///					{
        ///						type: &apos;line&apos;,
        ///						name: &apos;Luftfeuchte&apos;,
        ///						data: [
        ///.
        /// </summary>
        internal static string Graph_P2 {
            get {
                return ResourceManager.GetString("Graph_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///							],
        ///						yAxis: 1,
        ///						color: &apos;#8080A0&apos;
        ///					},
        ///					{
        ///						type: &apos;line&apos;,
        ///						name: &apos;Batteriespannung&apos;,
        ///						data: [.
        /// </summary>
        internal static string Graph_P3 {
            get {
                return ResourceManager.GetString("Graph_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 							],
        ///						yAxis: 2,
        ///						color: &apos;#8080A0&apos;
        ///					}
        ///				]
        ///			});
        ///			});
        ///		&lt;/script&gt;
        ///
        ///	&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;script src=&quot;http://code.highcharts.com/highcharts.js&quot;&gt;&lt;/script&gt;
        ///    &lt;div id=&quot;graph&quot;&gt;&lt;/div&gt;
        ///    &lt;br /&gt;
        ///    &lt;b&gt;
        ///.
        /// </summary>
        internal static string Graph_P4 {
            get {
                return ResourceManager.GetString("Graph_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/b&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Graph_P5 {
            get {
                return ResourceManager.GetString("Graph_P5", resourceCulture);
            }
        }
    }
}
